### ISSUE TITLE
Shopware 6 - State machine, sorting options, and salutations translations

### ISSUE THREAD

**Issue by sjef-letstalk** [boxblinkracer/phpunuhi#49]
Hi,

This is a feature request for non-snippet translations. Currently in Shopware 6 (6.6) not all translations are editable with the use of snippets. The following three sections are connected to the frontend for customers to see by default.

- For the State Machine they aren't even editable in the admin.
      Located in the `state_machine_state_translation` table
- The sorting options can be edited in the admin: Settings->Shop->Products
      Located in the `product_sorting_translation` table
- The salutations can be edited in the admin: Settings->Shop->Salutations
      Located in the `salutation_translation` table

There are more translations not using snippets, tables with `[...]_translation`. But those are data driven for example the categories and shopping experiences.

**Comment by boxblinkracer** [comment]
Hi

this is already doable, I totally forgot that during my talk at SCD haha
you can define any entity that has a _translation table and it will work (state machines)

so if you check out the latest README it has new samples in shopware-6

theres also a small bug already fixed in dev-master for shopware 6.6, 
but dev-master should work :)

**Comment by boxblinkracer** [comment]
so this is released in v 1.12.0
feel free to open it again if something is not working :)

**Comment by sjef-letstalk** [comment]
Thanks! And for the great talk at SCD 'also' 😃
